### ISSUE TITLE
Is the wiki for this still available?

### ISSUE THREAD

**Issue by njradford** [MarcinSc/gdx-graph#5]
seems to have disappeared from the GH page.

**Comment by mrlem** [comment]
I'd be curious about this too.

**Comment by MarcinSc** [comment]
I think the YouTube series is the best documentation for it. Also - the code has plenty of examples in gdx-graph-test module.

**Comment by mrlem** [comment]
Hi, and thanks for your answer, and for this tool, which looks awesome!

I'll try to dive into the videos, then, thanks.
I was actually looking for the wiki because of the README, which points to it.
